# Generated by Django 5.0.6 on 2024-07-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serveyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servey_question_detail',
            name='descriptions',
        ),
    ]
