# Generated by Django 5.0.6 on 2024-07-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serveyapp', '0002_remove_servey_question_detail_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='servey_question_detail',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
    ]
