# Generated by Django 5.0.6 on 2024-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_userrole_designation'),
        ('serveyapp', '0005_surveyanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(related_name='users', to='account.userrole')),
            ],
        ),
    ]
