# Generated by Django 5.0.6 on 2024-08-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serveyapp', '0006_createpanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='no_of_questions',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='options',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='question_type',
        ),
    ]
