# Generated by Django 5.0.6 on 2024-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveyapp', '0007_remove_surveyquestion_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='company',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='language',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
