# Generated by Django 5.0.6 on 2024-08-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveyapp', '0008_remove_surveyquestion_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='time_zone',
            new_name='incentive',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='mode_of_interview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='panels',
            field=models.ManyToManyField(related_name='surveys', to='serveyapp.createpanel'),
        ),
    ]
