# Generated by Django 5.0.6 on 2024-05-22 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_job_respondent_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'default_permissions': (), 'permissions': (('Sales dashboard', 'Sales dashboard'), ('Operation dashboard', 'Operation dashboard'), ('Finance dashboard', 'Finance dashboard'))},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default=datetime.datetime(2024, 5, 22, 6, 58, 16, 697752, tzinfo=datetime.timezone.utc), max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
