# Generated by Django 5.0.6 on 2024-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Industry Name'),
        ),
    ]
