# Generated by Django 5.0.6 on 2024-05-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_industry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='account.industry'),
        ),
    ]
