# Generated by Django 5.0.6 on 2024-06-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_usermodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
