# Generated by Django 5.0.6 on 2024-06-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'default_permissions': (), 'permissions': (('can_edit', 'Can Edit'), ('can_view', 'Can View'), ('can_create', 'Can Create'), ('can_delete', 'Can Delete'))},
        ),
    ]
