# Generated by Django 5.0.6 on 2024-06-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_userrole_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department', verbose_name='Industry'),
        ),
    ]
