# Generated by Django 5.0.6 on 2024-06-26 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_userrole_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry Hierarchy', 'verbose_name_plural': 'Industry Hierarchies'},
        ),
        migrations.AddField(
            model_name='industry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.industry'),
        ),
    ]
