# Generated by Django 5.0.6 on 2024-07-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_userrole_options_userrole_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user__username'], 'permissions': [('can_create', 'Can Create'), ('can_view', 'Can View'), ('can_edit', 'Can Edit'), ('can_delete', 'Can Delete'), ('can_approve', 'Can Approve'), ('can_reject', 'Can reject')]},
        ),
    ]
