# Generated by Django 5.0.6 on 2024-07-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_userrole_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
