# Generated by Django 5.0.6 on 2024-08-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_usermodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
    ]
