# Generated by Django 5.0.6 on 2024-08-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.designation'),
        ),
    ]
