# Generated by Django 5.0.6 on 2024-09-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_userrole_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='department',
        ),
    ]
