# Generated by Django 5.0.6 on 2024-09-10 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_userrole_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='userrole',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.industry'),
        ),
    ]
