# Generated by Django 5.0.6 on 2024-09-10 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0030_userpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('project_code', models.CharField(max_length=255, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('end_client_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_status', models.CharField(choices=[('Awarded', 'Awarded'), ('Live', 'Live'), ('Completed', 'Completed'), ('Pause', 'Pause')], default='Awarded', max_length=255)),
                ('id_received_date', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField()),
                ('client_po', models.CharField(blank=True, max_length=255, null=True)),
                ('max_number', models.IntegerField()),
                ('client_allocation', models.IntegerField()),
                ('client_project_number', models.CharField(blank=True, max_length=255, null=True)),
                ('end_client_project_number', models.CharField(blank=True, max_length=255, null=True)),
                ('programming_complexity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50)),
                ('currency_invoicing', models.CharField(choices=[('USD', 'USD (US Dollar)'), ('EUR', 'EUR (Euro)'), ('INR', 'INR (Indian Rupee)')], default='USD', max_length=50)),
                ('services', models.CharField(choices=[('Consulting', 'Consulting'), ('Development', 'Development'), ('Support', 'Support')], max_length=255)),
                ('management_fee', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], max_length=50)),
                ('description', models.TextField()),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userrole')),
                ('secondary_project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
