# Generated by Django 5.0.6 on 2024-07-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedentry',
            name='tags',
            field=models.ManyToManyField(to='feeds.tag'),
        ),
    ]
