# Generated by Django 5.0.6 on 2024-09-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_feedentry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedentry',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
