# Generated by Django 5.0.6 on 2024-09-06 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_userrole_designation'),
        ('feeds', '0005_feedentry_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='account.category'),
        ),
    ]
